on:
  - push
  - workflow_dispatch  # 수동 실행 활성화

name: Create Custom VM Image

jobs:
  build-image:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout
      uses: actions/checkout@v2    

    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Set active subscription
      run: |
        az account set --subscription 19eb594b-cdc5-4463-896e-5dbb5da01511

    - name: Create App Baked Image
      id: imageBuilder
      uses: azure/build-vm-image@v0
      with:
        location: 'koreacentral'
        resource-group-name: 'rg-aib-test-01'
        managed-identity: '/subscriptions/19eb594b-cdc5-4463-896e-5dbb5da01511/resourcegroups/rg-aib-test-01/providers/Microsoft.ManagedIdentity/userAssignedIdentities/mi-aib-test-01' # Managed identity
        source-os-type: 'windows'
        source-image-type: 'platformImage'
        source-image: MicrosoftWindowsServer:WindowsServer:2019-Datacenter:latest #unique identifier of source image
        dist-type: 'SharedImageGallery'
        dist-resource-id: '/subscriptions/19eb594b-cdc5-4463-896e-5dbb5da01511/resourceGroups/rg-aib-test-01/providers/Microsoft.Compute/galleries/acg_aib_test_01/images/img-def-test-01-v1/versions/0.1.1' #Replace with the resource id of your shared image  gallery's image definition
        dist-location: 'koreacentral'

    - name: Ensure Azure Login (Before VM Creation)
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set active subscription (Before VM Creation)
      run: |
        az account set --subscription 19eb594b-cdc5-4463-896e-5dbb5da01511
        az account show  # 현재 계정 정보 출력하여 확인

    - name: CREATE VM
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az account set --subscription 19eb594b-cdc5-4463-896e-5dbb5da01511
          az vm create --resource-group ghactions-vMimage  --name "app-vm-${{ GITHUB.RUN_NUMBER }}"  --admin-username testadmin --admin-password "${{ secrets.VM_PWD }}" --location  koreacentral --image "${{ steps.imageBuilder.outputs.custom-image-uri }}"
